apiVersion: v1 
kind: Service 
metadata:
  name: nginx-service       # Nombre del servicio, se puede cambiar pero debe coincidir con el backend del Ingress
spec: 
  type: LoadBalancer        # Tipo de servicio, LoadBalancer crea una IP pública en la nube para el acceso
  ports:
    - port: 80              # Puerto del servicio que estará disponible externamente
      targetPort: 80         # Puerto donde está escuchando el contenedor (debe coincidir con el puerto del contenedor en el Deployment)
  selector:
    app: nginx              # Selecciona los pods del Deployment con esta etiqueta
