apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-ingenieria-grpc
  namespace: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-ingenieria-grpc
  template:
    metadata:
      name: client-ingenieria-grpc
      labels:
        app: client-ingenieria-grpc
    spec:
      containers:
        - name: client-ingenieria-grpc
          image:  allangomez/client-inge:v0.5 #cambiar por la imagen de dockerhub
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-8080
  namespace: grpc-app
spec:
  selector:
    app: client-ingenieria-grpc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # O ClusterIP pero es que se no se puede acceder fuera del cluster
