apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mi-cluster-kafka #nombre que se le asigna al cluster
  namespace: kafka
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal #Significa que la comunicación es interna, es como el ClusterIP
        tls: false #No se habilita TLS para la comunicación interna
    storage: #Configuracion de Zookeeper, necesario para la coordinación de los brokers
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {} #gestiona los topics
    userOperator: {} #gestiona los usuarios
