apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: winners
  labels:
    strimzi.io/cluster: mi-cluster-kafka
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: losers
  labels:
    strimzi.io/cluster: mi-cluster-kafka
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
