[package]
name = "ingenieria"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = {version = "1.0",features = ["derive"]}
serde_json = "1.0"
tonic = "0.12"
tokio = {version = "1", features = ["full"]}
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"
