services:
  log_registry:
    build: ./
    container_name: log_container
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/code/logs
      - ./img:/code/img
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

